apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../components/statefulset
  - ../../components/service-aws-nlb-internal

patches:
  - path: storageclass-patch.yaml

images:
  - name: dbmarlin/dbmarlin-server
    newTag: 6.5.1 # Change this tag to upgrade DBmarlin
