apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbmarlin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # Overridden per overlay via storageclass-patch.yaml
  resources:
    requests:
      storage: 20Gi
