version: '4.1'

services:
  my-dbmarlin-server:
    image: dbmarlin/dbmarlin-server:latest
    platform: linux/amd64
    ports:
      - "9080:9080"
      - "9090:9090"
  my-dbmarlin-agent1:
    image: dbmarlin/dbmarlin-agent:latest
    platform: linux/amd64
    environment:
      DBMARLIN_AGENT_NAME: dbmarlin-remote-1
      DBMARLIN_ARCHIVER_URL: http://my-dbmarlin-server:9090/archiver
      DBMARLIN_API_KEY: 
  my-dbmarlin-agent2:
    image: dbmarlin/dbmarlin-agent:latest
    platform: linux/amd64
    environment:
      DBMARLIN_AGENT_NAME: dbmarlin-remote-2
      DBMARLIN_ARCHIVER_URL: http://my-dbmarlin-server:9090/archiver
      DBMARLIN_API_KEY: 