apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmarlin-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmarlin-agent
  template:
    metadata:
      labels:
        app: dbmarlin-agent 
    spec:
      containers:
      - name: dbmarlin-agent
        image: dbmarlin/dbmarlin-agent:latest
        env:
        - name: DBMARLIN_AGENT_NAME
          value: "k8s-test-agent"
        - name: DBMARLIN_ARCHIVER_URL
          value: "http://dbmarlin-server/archiver"
        - name: DBMARLIN_API_KEY
          value: ""
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"