apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmarlin-server
spec:
  template:
    spec:
      volumes:
      - name: dbmarlin-volume
        persistentVolumeClaim:
          claimName: dbmarlin-pvc
      initContainers:
      - name: dbmarlin-init
        image: dbmarlin/dbmarlin-server:5.1.0 # Pull a tag like 4.12.0 or latest
        volumeMounts:
        - mountPath: /opt/dbmarlin
          name: dbmarlin-volume
      containers:
      - name: dbmarlin-server
        image: dbmarlin/dbmarlin-server:5.1.0 # Should be same image as the init container above
        volumeMounts:
        - mountPath: /opt/dbmarlin
          name: dbmarlin-volume
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
