apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbmarlin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2  # Use gp2 storage class for AWS EKS