apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmarlin-server
spec:
  template:
    spec:
      initContainers:
        - name: dbmarlin-init
          image: dbmarlin/dbmarlin-server:latest
      containers:
        - name: dbmarlin-server
          image: dbmarlin/dbmarlin-server:latest
