apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmarlin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmarlin-server
  template:
    metadata:
      labels:
        app: dbmarlin-server
    spec:
      containers:
      - name: dbmarlin-server
        image: dbmarlin/dbmarlin-server:latest
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"