apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbmarlin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbmarlin-server
  template:
    metadata:
      labels:
        app: dbmarlin-server
    spec:
      volumes:
      - name: dbmarlin-volume
        persistentVolumeClaim:
          claimName: dbmarlin-pvc
      containers:
      - name: dbmarlin-server
        image: dbmarlin/dbmarlin-server:latest
        volumeMounts:
        - name: dbmarlin-volume
          mountPath: /opt/dbmarlin/data
        resources:
          limits:
            cpu: "1"
            memory: "1024Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          tcpSocket:
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 30
      restartPolicy: Always
