apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbmarlin-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /Users/mick/Documents/Kubernetes/dbmarlin-pvc
